// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ZhiHuApp.Models
{
    [JsonObject(MemberSerialization.OptIn)]
    public class ReplyTo
    {

        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }
    }
    [JsonObject(MemberSerialization.OptIn)]
    public class Comment
    {

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("avatar")]
        public string Avatar { get; set; }

        [JsonProperty("time")]
        public int Time { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("likes")]
        public int Likes { get; set; }

        [JsonProperty("reply_to")]
        public ReplyTo ReplyTo { get; set; }
    }
    [JsonObject(MemberSerialization.OptIn)]
    public class Comments
    {
        [JsonProperty("comments")]
        public IEnumerable<Comment> CommentList { get; set; }
    }
}
